# Generated by Django 6.0.5 on 2026-06-03 09:33

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image_1', models.ImageField(blank=True, help_text='Primary about image', null=True, upload_to='about/')),
                ('image_2', models.ImageField(blank=True, help_text='Secondary about image', null=True, upload_to='about/')),
                ('ceo_name', models.CharField(blank=True, max_length=100)),
                ('ceo_title', models.CharField(blank=True, max_length=100)),
                ('ceo_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('highlight_1_title', models.CharField(blank=True, default='Super Quality Food', max_length=100)),
                ('highlight_1_description', models.CharField(blank=True, max_length=255)),
                ('highlight_2_title', models.CharField(blank=True, default='Qualified Chef', max_length=100)),
                ('highlight_2_description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating should be between 1 and 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload high-quality images (recommended size: 1920x1080)', null=True, upload_to='gallery/%Y/%m/%d/')),
                ('media_url', models.URLField(blank=True, help_text='URL for embedded content (YouTube/Vimeo videos)')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('position', models.PositiveIntegerField(default=0, help_text='Position in category ordering (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.gallerycategory')),
            ],
            options={
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Recommended size 800×500', null=True, upload_to='events/%Y/%m/')),
                ('venue', models.CharField(blank=True, help_text='Specific venue ', max_length=200)),
                ('start_datetime', models.DateTimeField(help_text='Event start date & time')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Event end date & time (optional)', null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for free events', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('past', 'Past'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['status', 'start_datetime'], name='core_event_status_b1eba0_idx'), models.Index(fields=['status'], name='core_event_status_10b7b9_idx'), models.Index(fields=['is_active', 'status'], name='core_event_is_acti_680c67_idx')],
            },
        ),
    ]
