# Generated by Django 6.0.5 on 2026-06-08 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactreply_alter_sitesettings_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='chat_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of a chat or message from this person', null=True, upload_to='testimonials/screenshots/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text Review'), ('screenshot', 'Chat Screenshot'), ('video', 'Video Testimonial')], db_index=True, default='text', help_text='How the testimonial content is displayed', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_file',
            field=models.FileField(blank=True, help_text='Short testimonial video (MP4 recommended, ≤50 MB)', null=True, upload_to='testimonials/videos/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/profiles/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_active', '-created_at'], name='core_testim_is_acti_820d52_idx'),
        ),
    ]
