# Generated by Django 6.0.5 on 2026-06-10 05:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='video_file',
            field=models.FileField(blank=True, help_text='Short testimonial video (MP4/WebM/OGG/MOV, ≤50 MB)', null=True, upload_to='testimonials/videos/', validators=[core.validators.validate_video_upload]),
        ),
    ]
