# Generated by Django 6.0.5 on 2026-06-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=100)),
                ('python_community_member', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('python_community_name', models.CharField(blank=True, max_length=200)),
                ('experience_level', models.CharField(choices=[('complete_beginner', 'Complete beginner (I have never coded in Python)'), ('beginner', 'Beginner (I have written basic Python — print statements, variables)'), ('intermediate', 'Intermediate (I am familiar with loops, functions, and basic projects)'), ('advanced', 'Advanced (I am comfortable with OOP, data structures, and libraries)')], max_length=20)),
                ('programming_experience', models.TextField(blank=True)),
                ('mentorship_stream', models.CharField(choices=[('beginner', 'Stream 1: Beginner Zero to Hero (no prior Python knowledge needed)'), ('specialty', 'Stream 2: Specialty Zero to Hero (requires at least intermediate Python knowledge)')], max_length=20)),
                ('tech_interests', models.CharField(max_length=500)),
                ('reason_for_joining', models.TextField()),
                ('schedule_commitment', models.CharField(choices=[('yes', 'Yes, I can commit'), ('no', 'No, I cannot commit'), ('unsure', "I'm not sure")], max_length=10)),
                ('device_access', models.CharField(choices=[('yes', 'Yes, I have reliable access'), ('no', 'No'), ('partial', 'I have partial access (shared device or inconsistent internet)')], max_length=10)),
                ('referral_source', models.CharField(choices=[('black_python_dev', 'Black Python Dev website / social media'), ('friend_colleague', 'Friend or colleague'), ('whatsapp_group', 'WhatsApp group'), ('online_search', 'Online search'), ('other', 'Other')], max_length=20)),
                ('referral_other', models.CharField(blank=True, max_length=200)),
                ('questions_concerns', models.TextField(blank=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
