# Generated by Django 6.0.5 on 2026-06-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mentorshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipapplication',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Private internal notes'),
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='internal_score',
            field=models.IntegerField(default=0, help_text='Score from 1 to 5'),
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('interview', 'Interviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20),
        ),
    ]
