# Generated by Django 6.0.5 on 2026-06-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mentorshipapplication_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipapplication',
            name='tech_interests',
            field=models.JSONField(default=list),
        ),
    ]
