# Generated by Django 6.0.5 on 2026-06-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mentorshipapplication_tech_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
