# Generated by Django 6.0.5 on 2026-06-18 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_mentorshipapplication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL for embedded content (YouTube/Vimeo videos)', validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AlterField(
            model_name='mentorshipapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
