# Generated by Django 6.0.5 on 2026-06-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=25)),
                ('tier_interest', models.CharField(choices=[('bronze', 'Bronze (₦150,000)'), ('silver', 'Silver (₦350,000)'), ('gold', 'Gold (₦750,000)'), ('platinum', 'Platinum (₦1,500,000)'), ('in_kind', 'In-Kind Sponsorship'), ('undecided', 'Undecided / Custom')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Specific goals or in-kind details')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sponsorship Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
