# Generated by Django 6.0.5 on 2026-06-19 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sponsorshipinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_display', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Enter each feature on a new line')),
                ('is_recommended', models.BooleanField(default=False)),
                ('icon_class', models.CharField(default='fas fa-gem', max_length=50)),
                ('bg_class', models.CharField(blank=True, help_text='e.g. bronze-bg, silver-bg', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='sponsorshipinquiry',
            name='tier_interest',
        ),
        migrations.AddField(
            model_name='sponsorshipinquiry',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sponsorshiptier'),
        ),
    ]
