# Generated by Django 6.0.5 on 2026-06-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sponsorshiptier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='ceo_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ceo_name',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ceo_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='highlight_1_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='highlight_1_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='highlight_2_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='highlight_2_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='signature_image',
        ),
    ]
