# Generated by Django 6.0.5 on 2026-06-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_aboutpage_ceo_image_remove_aboutpage_ceo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL (optional)', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL (optional)', null=True),
        ),
    ]
