# Generated by Django 6.0.5 on 2026-06-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_testimonial_linkedin_url_testimonial_twitter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail for the video. If left blank, the first frame of the video will be used.', null=True, upload_to='testimonials/thumbnails/'),
        ),
    ]
