# Generated by Django 6.0.5 on 2026-06-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_testimonial_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=100)),
                ('linkedin_profile', models.URLField()),
                ('github_profile', models.URLField(blank=True)),
                ('role_interest', models.CharField(choices=[('mentor', 'Mentor (Python Expert)'), ('teaching_assistant', 'Teaching Assistant'), ('career_coach', 'Career Coach / Industry Mentor'), ('community_liaison', 'Community Liaison / Manager'), ('graphics_social', 'Graphics Designer & Social Media Manager'), ('content_writer', 'Content Writer / Technical Writer'), ('other', 'Other')], max_length=50)),
                ('role_other', models.CharField(blank=True, max_length=200)),
                ('job_title_company', models.CharField(max_length=200)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('areas_of_expertise', models.JSONField(default=list)),
                ('professional_bio', models.TextField()),
                ('motivation', models.TextField()),
                ('hours_per_week', models.CharField(choices=[('2_4', '2–4 hours'), ('5_8', '5–8 hours'), ('8_plus', '8+ hours')], max_length=20)),
                ('evening_availability', models.CharField(choices=[('yes', 'Yes'), ('partially', 'Partially'), ('no', 'No')], max_length=20)),
                ('commitment_length', models.CharField(choices=[('6_months', 'Full 6 months (Preferred)'), ('3_months', '3 months'), ('flexible', 'Flexible')], max_length=20)),
                ('cv_resume', models.FileField(blank=True, help_text='Upload CV / Resume (PDF)', null=True, upload_to='volunteers/cvs/')),
                ('additional_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('interview', 'Interviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('internal_score', models.IntegerField(default=0, help_text='Score from 1 to 5')),
                ('admin_notes', models.TextField(blank=True, help_text='Private internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
