# Generated by Django 6.0.5 on 2026-06-23 11:36

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_volunteerapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Volunteer Application', 'verbose_name_plural': 'Volunteer Applications'},
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='cv_resume',
            field=models.FileField(blank=True, help_text='Upload CV / Resume (PDF, max 10 MB)', null=True, upload_to='volunteers/cvs/', validators=[core.validators.validate_pdf_upload]),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('interview', 'Interviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], db_index=True, default='pending', max_length=20),
        ),
    ]
