# Generated by Django 6.0.5 on 2026-06-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_volunteerapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='interview_booking_link',
            field=models.URLField(blank=True, help_text='Calendly or scheduling link for interviews', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
