# Generated by Django 6.0.5 on 2026-06-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='url_hash',
            field=models.CharField(max_length=64, unique=True, verbose_name='Url'),
        ),
    ]
