# Generated by Django 6.0.5 on 2026-06-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional. Overrides the meta description. Recommended max 155 characters.', max_length=165),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional. Overrides the page &lt;title&gt;. Recommended max 60 characters.', max_length=70),
        ),
    ]
